function list = nrf5_getlist ()
device_list = [];

% NOTE:
% Run: "clear all" to apply change

% =========================================================================
% Source files and include
% =========================================================================

% --- nrf51 ---
% Generic
nrf51_inc_dir = {...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','drivers_nrf','delay'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','toolchain'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','toolchain','cmsis','include'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','softdevice','s310','headers'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','softdevice','common','softdevice_handler'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','drivers_nrf','hal'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','drivers_nrf','twi_master'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','drivers_nrf','config'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','drivers_nrf','common'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','libraries','util'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','libraries','timer'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','device')...
    };
nrf51_src_dir = {...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','softdevice','common','softdevice_handler'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','toolchain'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','libraries','timer'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','libraries','util'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','drivers_nrf','delay')...
    };
nrf51_src_files = {...
    'softdevice_handler',...
    'app_timer.c',...
    'app_error.c',...
    'nrf_delay.c',...
    'system_nrf51.c'...    
    };

% ANT
nrf51_ant_inc_dir = {...
    };
nrf51_ant_src_dir = {...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','softdevice','common','softdevice_handler'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','toolchain'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','libraries','util'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','libraries','timer'),...
    fullfile(nrf5root,'utils','nRF51_SDK_10.0.0','components','drivers_nrf','delay')...
    };
nrf51_ant_src_files = {...
    'nrf_delay.c','system_nrf51.c','app_error.c','app_timer.c','softdevice_handler.c'...
    };

% --- nrf52 ---
% Generic
nrf52_inc_dir = {...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx','mdk'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','integration','nrfx'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','integration','nrfx','legacy'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx','hal'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx','soc'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx','drivers'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx','drivers','include'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx','drivers','src','prs'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','toolchain','cmsis','include'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','strerror'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','experimental_section_vars'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','softdevice','s132','headers'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','softdevice','common'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','util'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','fifo'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','uart'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','util'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','delay'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','timer'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','balloc'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','log'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','pwr_mgmt'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','mutex'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','log','src'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','experimental_log'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','experimental_log','src'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','experimental_memobj'),...
    };
nrf52_src_dir = {...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx','drivers','src'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx','mdk'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','integration','nrfx','legacy'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx','drivers','src'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','modules','nrfx','drivers','src','prs'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','softdevice','common'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','strerror'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','util'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','fifo'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','uart'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','util'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','timer'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','pwr_mgmt'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','experimental_section_vars'),...    
    };
nrf52_src_files = {...
    'nrf_pwr_mgmt.c',...
    'nrfx_prs.c',...
    'nrfx_twi.c',...
    'nrfx_spi.c',...
    'nrfx_uart.c',...
    'nrfx_uarte.c',...
    'app_fifo.c',...
    'app_uart_fifo.c',...
    'nrf_drv_spi.c',...
    'nrf_drv_twi.c',...
    'nrf_drv_uart.c',...
    'nrfx_spim.c',...
    'nrfx_saadc.c',...
    'system_nrf52.c',...
    'app_error.c',...
    'app_error_weak.c',...
    'app_util_platform.c',...
    'nrf_assert.c',...
    'nrf_strerror.c',...
    'app_timer.c',...
    'nrf_sdh.c',...
    'nrf_sdh_soc.c',...
    'nrf_section_iter.c',...
    'nrf_common.ld'...
    };

% BLE
nrf52_ble_inc_dir = {...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic_fifo'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','fstorage'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic_flags'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','common'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_advertising'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_link_ctx_manager'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','nrf_ble_gatt'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','nrf_ble_qwr'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_services','ble_nus')...
    };

nrf52_ble_src_dir = {...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic_fifo'),...    
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','fstorage'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic_flags'),...    
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','common'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_advertising'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_link_ctx_manager'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','nrf_ble_gatt'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','nrf_ble_qwr'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_services','ble_nus')...
    };

nrf52_ble_src_files = {...
    'ble_advdata.c',...
    'ble_advertising.c',...
    'ble_conn_params.c',...
    'ble_conn_state.c',...
    'ble_link_ctx_manager.c',...
    'ble_srv_common.c',...
    'nrf_ble_gatt.c',...
    'nrf_ble_qwr.c',...
    'ble_nus.c',...
    'nrf_sdh_ble.c',...
    'nrf_atflags.c',...
    'nrf_atomic.c',...
    'nrf_fstorage.c',...
    'nrf_fstorage_sd.c',...
    'nrf_atfifo.c'...
    };

% BLE_C
nrf52_ble_c_inc_dir = {
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_db_discovery'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','nrf_ble_scan'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_services','ble_nus_c'),...
    };

nrf52_ble_c_src_dir = {
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_db_discovery'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','nrf_ble_scan'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_services','ble_nus_c'),...
    };
    
nrf52_ble_c_src_files = {
    'ble_db_discovery.c',...
    'nrf_ble_scan.c',...
    'ble_nus_c.c'
    };

% DFU
nrf52_dfu_inc_dir = {...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','softdevice','common'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','softdevice','s132','headers','nrf52'),...    
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','common'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_advertising'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','peer_manager'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','nrf_ble_gatt'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','nrf_ble_qwr'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','peer_manager'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_services'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_services','ble_nus'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_link_ctx_manager'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_services','ble_dfu'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','mutex'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','crc16'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','fds'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','svc'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic_fifo'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic_flags'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','balloc'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','fstorage'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','experimental_memobj'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','pwr_mgmt'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','experimental_section_vars'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','bootloader'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','bootloader','dfu'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','bootloader','ble_dfu')...
    };

nrf52_dfu_src_dir = {...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','common'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_advertising'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','peer_manager'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','nrf_ble_gatt'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','nrf_ble_qwr'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','peer_manager'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_services'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_services','ble_nus'),...    
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_link_ctx_manager'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','ble','ble_services','ble_dfu'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','crc16'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','fds'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic_fifo'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic_flags'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','atomic'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','balloc'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','fstorage'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','experimental_memobj'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','pwr_mgmt'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','experimental_section_vars'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','bootloader','dfu'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','softdevice','common')...  
    };

nrf52_dfu_src_files = {...
    'app_error_handler.c',...    
    'ble_advdata.c',...
    'ble_advertising.c',...
    'ble_conn_params.c',...
    'ble_conn_state.c',...
    'ble_srv_common.c',...
    'gatt_cache_manager.c',...
    'gatts_cache_manager.c',...
    'id_manager.c',...
    'nrf_ble_gatt.c',...
    'nrf_ble_qwr.c',...
    'peer_data_storage.c',...
    'peer_database.c',...
    'peer_id.c',...
    'peer_manager.c',...
    'pm_buffer.c',...
    'pm_mutex.c',...
    'security_dispatcher.c',...
    'security_manager.c',...
    'ble_nus.c',...
    'ble_link_ctx_manager.c',...
    'ble_dfu.c',...
    'ble_dfu_bonded.c',...
    'ble_dfu_unbonded.c',...
    'crc16.c',...
    'fds.c',...
    'nrf_atfifo.c',...
    'nrf_atflags.c',...
    'nrf_atomic.c',...
    'nrf_balloc.c',...
    'nrf_fstorage.c',...
    'nrf_fstorage_sd.c',...
    'nrf_memobj.c',...
    'nrf_pwr_mgmt.c',...
    'nrf_section_iter.c',...
    'nrf_dfu_svci.c',...
    'nrf_sdh.c',...
    'nrf_sdh_ble.c',...
    'nrf_sdh_soc.c'...
    };

% MESH
nrf52_mesh_inc_dir = {...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','examples'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','examples','serial','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','examples','common','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','models','config','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','models','health','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','stack','api'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','core','api'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','core','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','access','api'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','access','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','dfu','api'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','dfu','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','prov','api'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','prov','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','bearer','api'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','bearer','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','gatt','api'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','gatt','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','serial','api'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','serial','include'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','softdevice','common'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','softdevice','s132','headers','nrf52'),...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','fds'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','external','rtt','include'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','external','micro-ecc')...
    };

nrf52_mesh_src_dir = {...
    fullfile(nrf5root,'utils','nRF5_SDK_15.2.0','components','libraries','util'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','examples'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','examples','common','src'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','core','src'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','serial','src'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','stack','src'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','access','src'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','bearer','src'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','external','rtt','src'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','mesh','prov','src'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','models','config','src'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','models','health','src'),...
    fullfile(nrf5root,'utils','nrf5_SDK_for_Mesh_v2.0.0','external','micro-ecc')...
    };

%    'mesh_softdevice_init.c',
%    'app_error_weak.c',
nrf52_mesh_src_files = {...
    'mesh_provisionee.c',...
    'nrf_mesh_weak.c',...
    'assertion_handler_weak.c',...
    'internal_event.c',...
    'nrf_mesh_configure.c',...
    'aes.c',...
    'msg_cache.c',...
    'transport.c',...
    'event.c',...
    'packet_buffer.c',...
    'flash_manager_defrag.c',...
    'fifo.c',...
    'nrf_flash.c',...
    'packet_mgr.c',...
    'net_state.c',...
    'mesh_flash.c',...
    'nrf_mesh_utils.c',...
    'nrf_mesh.c',...
    'queue.c',...
    'hal.c',...
    'aes_cmac.c',...
    'timer_scheduler.c',...
    'timer.c',...
    'ticker.c',...
    'rand.c',...
    'nrf_mesh_opt.c',...
    'timeslot.c',...
    'bearer_event.c',...
    'enc.c',...
    'network.c',...
    'net_packet.c',...
    'msqueue.c',...
    'nrf_mesh_keygen.c',...
    'cache.c',...
    'uri.c',...
    'list.c',...
    'log.c',...
    'flash_manager.c',...
    'ccm_soft.c',...
    'toolchain.c',...
    'replay_cache.c',...
    'beacon.c',...
    'flash_manager_internal.c',...
    'core_tx.c',...
    'heartbeat.c',...
    'net_beacon.c',...
    'fsm.c',...
    'core_tx_adv.c',...
    'serial_uart.c',...
    'serial_bearer.c',...
    'serial_handler_common.c',...
    'serial_handler_access.c',...
    'serial_handler_config.c',...
    'serial_handler_openmesh.c',...
    'serial.c',...
    'serial_handler_prov.c',...
    'serial_handler_dfu.c',...
    'serial_handler_mesh.c',...
    'serial_handler_models.c',...
    'serial_handler_device.c',...
    'nrf_mesh_serial.c',...
    'serial_handler_app.c',...
    'mesh_stack.c',...
    'access_publish.c',...
    'access.c',...
    'access_reliable.c',...
    'device_state_manager.c',...
    'ad_listener.c',...
    'ad_type_filter.c',...
    'adv_packet_filter.c',...
    'advertiser.c',...
    'bearer_handler.c',...
    'broadcast.c',...
    'filter_engine.c',...
    'gap_address_filter.c',...
    'radio_config.c',...
    'rssi_filter.c',...
    'scanner.c',...
    'SEGGER_RTT.c',...
    'SEGGER_RTT_printf.c',...
    'uECC.c',...
    'prov_provisioner.c',...
    'prov_provisionee.c',...
    'nrf_mesh_prov.c',...
    'provisioning.c',...
    'prov_beacon.c',...
    'prov_utils.c',...
    'prov_bearer_adv.c',...
    'composition_data.c',...
    'config_server.c',...
    'packed_index_list.c',...
    'health_server.c',...
    'app_error_handler.c',...
    'app_error.c',...
    'platform-specific.inc',...
    'curve-specific.inc',...
    'asm_arm.inc',...
    'uECC.c'...
    };

% =========================================================================
% Add Device MCU part list
% =========================================================================

% === nRF51422QFAA (16kB/256kB) ===
device_info = [];
device_info.family = 'nrf51';
device_info.name = 'nRF51422QFAA (16kB/256kB)';
device_info.softdevice = 'S310';
device_info.pincount = 48;
device_info.package = 'QFN';
device_info.flashsize = 128*1024; % 128kB
device_info.flash_origin = hex2dec('1D000');
device_info.ramsize = hex2dec('1C00'); % < 16kB
device_info.ram_origin = hex2dec('20002400');
device_info.define = {'NRF51'};
device_info.inc_dir = nrf51_inc_dir;
device_info.src_dir = nrf51_src_dir;
device_info.src_files = nrf51_src_files;
device = nrf5_create_mcu(device_info);
device_list{end+1} = device; % add to list

% Generic
device_info.define = {...
    'NRF51',...
    'S310',...
    'SOFTDEVICE_PRESENT',...
    'SWI_DISABLE0'...
    };
device_info.inc_dir = nrf51_inc_dir;
device_info.src_dir = nrf51_src_dir;
device_info.src_files = nrf51_src_files;

% Specific: ANT
device_info.specific_ant_define = {...
    };
device_info.specific_ant_inc_dir = nrf51_ant_inc_dir;
device_info.specific_ant_src_dir = nrf51_ant_src_dir;
device_info.specific_ant_src_files = nrf51_ant_src_files;

% =========================================================================
% === nRF52832QFAA (S132 v6) ===
device_info = [];
device_info.family = 'nrf52';
device_info.name = 'nRF52832QFAA (S132-v6)';
device_info.softdevice = 'S132';
device_info.pincount = 48;
device_info.package = 'QFN';
device_info.flashsize = hex2dec('40000');
device_info.flash_origin = hex2dec('26000');
device_info.ramsize = hex2dec('B000');
%device_info.ram_origin = hex2dec('200032C8'); %1628
device_info.ram_origin = hex2dec('20005000'); %1628

% Generic
device_info.define = {...
    'CONFIG_GPIO_AS_PINRESET',...
    'FLOAT_ABI_HARD',...
    'NRF52',...
    'NRF52832_XXAA',...
    'NRF52_PAN_74',...
    'S132',...
    'SOFTDEVICE_PRESENT',...
    'SWI_DISABLE0',...
    'CONFIG_NFCT_PINS_AS_GPIOS'...
    };
device_info.inc_dir = nrf52_inc_dir;
device_info.src_dir = nrf52_src_dir;
device_info.src_files = nrf52_src_files;

% Specific: BLE
device_info.specific_ble_define = {...
    'NRF_SD_BLE_API_VERSION=6'...
    };
device_info.specific_ble_inc_dir = nrf52_ble_inc_dir; % nrf52_ble_inc_dir
device_info.specific_ble_src_dir = nrf52_ble_src_dir;
device_info.specific_ble_src_files = nrf52_ble_src_files;

% Specific: BLE_C
device_info.specific_ble_c_define = {
    
    };
device_info.specific_ble_c_inc_dir = nrf52_ble_c_inc_dir;
device_info.specific_ble_c_src_dir = nrf52_ble_c_src_dir;
device_info.specific_ble_c_src_files = nrf52_ble_c_src_files;

% Specific: DFU
device_info.specific_dfu_define = {...
    'BL_SETTINGS_ACCESS_ONLY',...
    'NRF_DFU_SVCI_ENABLED',...
    'NRF_DFU_TRANSPORT_BLE=1'...
    };
device_info.specific_dfu_inc_dir = nrf52_dfu_inc_dir;
device_info.specific_dfu_src_dir = nrf52_dfu_src_dir;
device_info.specific_dfu_src_files = nrf52_dfu_src_files;

% Specific: MESH
%    'BEARER_ACCESS_ADDR_DEFAULT=0xCE930898U',...
device_info.specific_mesh_define = {...
    'CONFIG_APP_IN_CORE',...
    'NRF_MESH_LOG_ENABLE=NRF_LOG_USES_RTT',...
    'PERSISTENT_STORAGE=0',...
    'NRF52_SERIES',...
    'NRF52832',...
    'SD_BLE_API_VERSION=6',...
    'NRF_SD_BLE_API_VERSION=6',...
    'uECC_OPTIMIZATION_LEVEL=2',...
    'uECC_SUPPORTS_secp160r1=0',...
    'uECC_SUPPORTS_secp192r1=0',...
    'uECC_SUPPORTS_secp224r1=0',...
    'uECC_SUPPORTS_secp256r1=1',...
    'uECC_SUPPORTS_secp256k1=0',...
    'uECC_SUPPORT_COMPRESSED_POINT=0'...
    };
device_info.specific_mesh_inc_dir = nrf52_mesh_inc_dir;
device_info.specific_mesh_src_dir = nrf52_mesh_src_dir;
device_info.specific_mesh_src_files = nrf52_mesh_src_files;

device = nrf5_create_mcu(device_info);
device_list{end+1} = device; % add to list

%% Return
list = device_list;

% NOTE:
% Run: "clear all" to apply change

