function blkStruct = slblocks
	blkStruct.Name    = sprintf('Waijung Blockset');
	blkStruct.OpenFcn = 'waijung_blockset';
	blkStruct.MaskInitialization = '';
	blkStruct.MaskDisplay = 'disp(''Waijung Blockset'')';
	% Define the library list for the Simulink Library browser.
	% Return the name of the library model and the name for it
	Browser(1).Library = 'waijung_blockset';
	Browser(1).Name    = 'Waijung Blockset';
	Browser(1).IsFlat  = 0;
	blkStruct.Browser = Browser;
	clear Browser;
	
	% If there is problem with Simulink library browser not showing correctly
	% (after Refresh tree command). Try the following solution.
	%
	% reference: http://www.mathworks.com/matlabcentral/answers/8182
	%
	% This could be the result of a corruption of the library browser repositories. These can be regenerated by deleting or renaming the library browser information stored in the preferences directory.
	%
	% Rename the following directories:
	%
	% disp([prefdir '\sl_library_browser_repos'])
	% disp([prefdir '\sl_library_browser_favorite'])
	% Rename the following file:
	%
	% disp([prefdir '\sl_library_browser_lockfile'])
	% for example, I renamed sl_library_browser_repos to old_sl_library_browser_repos.